name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "Iniciando login dockerhub"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "Fin del login"
    - name: build docker
      run: |
        docker build --tag germanmoran/docker-grapql:0.0.2 .
        docker build --tag germanmoran/docker-grapql:latest .
    - name: push image
      run: |
        docker push germanmoran/docker-grapql:0.0.2
        docker build --tag germanmoran/docker-grapql:latest 

