name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v4.0.3
      with:
        major_pattern: "major: "
        minor_pattern: "feat: "
        format: "${major}.${minor}.${patch}-prerelease${increment}"
      id: version
      

    - name: login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        NER_VERSION: ${{steps.versions.outputs.version}}
      run: |
        echo "Iniciando login dockerhub"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "NEW VERSION: "$NEW_VERSION
        echo "Fin del login"
   # - name: build docker
   #   run: |
   #     docker build --tag germanmoran/docker-grapql:0.0.2 .
   #     docker build --tag germanmoran/docker-grapql:latest .
   # - name: push image
   #   run: |
   #     docker push germanmoran/docker-grapql:0.0.2
   #     docker build --tag germanmoran/docker-grapql:latest 

